### PR TITLE
Add stacked bar plot to viz module

### PR DESCRIPTION
**Pull request by mariecrane**
Updated viz.R, run_viz.py, and cli.py to include a stacked bar plot option. Updated dev_environment.yaml to include r-tidyr and r-dplyr packages

### CODE REVIEW

**Comment by mariecrane** [comment]
@jj-umn I'm not sure how to request a reviewer but would you be willing to take a look at this and merge if it looks okay?

**Comment by jj-umn** [comment]
@mariecrane @pravs3683   Are pull requests 34 and 35 compatible?   Are the changes backward compatible?  We should increase the version number in setup.py

**Comment by jj-umn** [comment]
@mariecrane Let's update the version in setup.py to VERSION = '1.1.0'

**Comment by mariecrane** [comment]
@jj-umn done!

**Review by jj-umn — APPROVED** [review]

**Pull request merged**
